### ISSUE TITLE
Colorize causes problems to latest SwiftFormat plugin for Danger

### ISSUE THREAD

**Issue by Panajev** [garriguv/danger-ruby-swiftformat#9]
Hello @garriguv  @mgrebenets  @nickdomenicali ,

Unfortunately, even after the update to the latest colorize, I am having problems with the plugin's use of colorize (I do not wanto suggest if one of the forks that are now keeping the plugin in active development, name slightly changed in the successful long running forks I have seen in the project's Network tab on GitHub).

The error I get now is:
```
20:02:04 /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/colored-1.2/lib/colored.rb:70:in `colorize': Danger::DSLError
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/colorize-0.8.1/lib/colorize/class_methods.rb:98:in `block (2 levels) in color_methods'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/xcov-1.4.3/lib/xcov/ignore_handler.rb:43:in `rescue in read_ignore_file'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/xcov-1.4.3/lib/xcov/ignore_handler.rb:40:in `read_ignore_file'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/xcov-1.4.3/lib/xcov/ignore_handler.rb:10:in `initialize'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-xcov-0.4.1/lib/danger_plugin.rb:58:in `new'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-xcov-0.4.1/lib/danger_plugin.rb:58:in `produce_report'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-xcov-0.4.1/lib/danger_plugin.rb:36:in `report'
20:02:04 	from Dangerfile:18:in `block in parse'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:200:in `eval'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:196:in `instance_eval'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:196:in `parse'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:274:in `run'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.4/lib/danger/danger_core/executor.rb:28:in `run'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.4/lib/danger/commands/runner.rb:68:in `run'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.4/bin/danger:5:in `<top (required)>'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin/danger:23:in `load'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin/danger:23:in `<main>'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
20:02:04 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

The gem env on that machine is:
```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.14
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-darwin17]
  - INSTALLATION DIRECTORY: /Users/mdbuildserver/.rvm/gems/ruby-2.3.3
  - USER INSTALLATION DIRECTORY: /Users/mdbuildserver/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/mdbuildserver/.rvm/rubies/ruby-2.3.3/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin
  - SPEC CACHE DIRECTORY: /Users/mdbuildserver/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/mdbuildserver/.rvm/rubies/ruby-2.3.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-17
  - GEM PATHS:
     - /Users/mdbuildserver/.rvm/gems/ruby-2.3.3
     - /Users/mdbuildserver/.rvm/gems/ruby-2.3.3@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin
     - /Users/mdbuildserver/.rvm/gems/ruby-2.3.3@global/bin
     - /Users/mdbuildserver/.rvm/rubies/ruby-2.3.3/bin
     - /bin
     - /Users/mdbuildserver/.cargo/bin
     - /Users/mdbuildserver/NativeNewStarter/scripts
     - /Users/mdbuildserver/NativeNewStarter/scripts/cli-tools
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/local/opt/ruby/bin
     - /Users/mdbuildserver/Library/Android/sdk/tools
     - /Users/mdbuildserver/Library/Android/sdk/platform-tools
     - /Users/mdbuildserver/Library/Android/sdk/build-tools/28.0.2
     - /Users/mdbuildserver/gradle/latest/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/X11/bin
     - /Users/mdbuildserver/.local/bin
     - /usr/local/Cellar/sonar-runner/2.4/libexec/bin
     - /Users/mdbuildserver/.cargo/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /usr/local/git/bin
     - /Users/mdbuildserver/.rvm/bin
```

The error Danger displays on GitHub is still:
```
[!] Invalid Dangerfile file: no implicit conversion of Hash into String
```

Reverting back to v0.3.3 fixes it.

**Comment by Panajev** [comment]
Hello, updated to the latest gem and the error is now:
```
Running Danger...
/Users/mdbuildserver/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:199:in `spawn': [0;31;49m (Danger::DSLError)
[!] Invalid `Dangerfile` file: No such file or directory - swiftformat[0m
 #  from Dangerfile:13
 #  -------------------------------------------
 #  --disable blankLinesAroundMark,hoistPatternLet,redundantParens,redundantVoidReturnType,trailingClosures" # optional
 >  swiftformat.check_format(fail_on_error: true)
 #  
 #  -------------------------------------------
	from /Users/mdbuildserver/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
	from /Users/mdbuildserver/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:95:in `popen3'
	from /Users/mdbuildserver/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:258:in `capture3'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-swiftformat-0.3.5/lib/swiftformat/cmd.rb:7:in `run'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-swiftformat-0.3.5/lib/swiftformat/swiftformat.rb:10:in `installed?'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-swiftformat-0.3.5/lib/swiftformat/plugin.rb:30:in `check_format'
	from Dangerfile:13:in `block in parse'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/danger_core/dangerfile.rb:200:in `eval'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/danger_core/dangerfile.rb:196:in `instance_eval'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/danger_core/dangerfile.rb:196:in `parse'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/danger_core/dangerfile.rb:274:in `run'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/danger_core/executor.rb:28:in `run'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/commands/runner.rb:68:in `run'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/bin/danger:5:in `<top (required)>'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin/danger:23:in `load'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin/danger:23:in `<main>'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
[!] The exception involves the following plugins:
 -  danger-swiftformat
```

**Comment by Panajev** [comment]
I think that last one was a stupid one... on that agent the swiftformat brew was missing... closing this issue unless we run into real problems with v0.3.5 when outputting a Swift format error in the GitHub PR. Thanks for addressing the issue!

**Comment by Panajev** [comment]
If there is an update or a further error I will reopen.

**Comment by garriguv** [comment]
Ok :smiley: Glad you solved the issue!

**Comment by Panajev** [comment]
Hey @garriguv 

This is driving me a bit insane now haha...
```
19:21:23 No lintable files found at path '/Users/mdbuildserver/Jenkins/workspace/tests-LobbyModule-all-commits-ios-pr/NativeLobby/ViewControllers/LobbyViewController.swift'
19:21:26 /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/colored-1.2/lib/colored.rb:70:in `colorize': Danger::DSLError
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/colorize-0.8.1/lib/colorize/class_methods.rb:98:in `block (2 levels) in color_methods'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/xcov-1.4.3/lib/xcov/ignore_handler.rb:43:in `rescue in read_ignore_file'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/xcov-1.4.3/lib/xcov/ignore_handler.rb:40:in `read_ignore_file'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/xcov-1.4.3/lib/xcov/ignore_handler.rb:10:in `initialize'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-xcov-0.4.1/lib/danger_plugin.rb:58:in `new'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-xcov-0.4.1/lib/danger_plugin.rb:58:in `produce_report'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-xcov-0.4.1/lib/danger_plugin.rb:36:in `report'
19:21:26 	from Dangerfile:18:in `block in parse'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/danger_core/dangerfile.rb:200:in `eval'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/danger_core/dangerfile.rb:196:in `instance_eval'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/danger_core/dangerfile.rb:196:in `parse'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/danger_core/dangerfile.rb:274:in `run'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/danger_core/executor.rb:28:in `run'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/lib/danger/commands/runner.rb:68:in `run'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/gems/danger-5.6.5/bin/danger:5:in `<top (required)>'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin/danger:23:in `load'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin/danger:23:in `<main>'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
19:21:26 	from /Users/mdbuildserver/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

Not sure why danger-xcov is in the middle of the stacktrace... colorize is a dependency only of danger-swiftformat, but it looks like if I have it installed (danger-swiftformat >= 0.3.4 requires colorize) then other plugins do not work correctly, but if I downgrade (uninstall all versions of danger-swiftformat and colorize and install the older version of danger-swiftformat ```gem install danger-swiftformat -v 0.3.3``` then it works again). Are these plugins conflicting with each other because of colorize?

**Comment by mgrebenets** [comment]
Hi @Panajev 
I've noticed that plugin already depends on `colored2`:

```
# Gemfile.lock
    cork (0.3.0)
      colored2 (~> 3.1)
```

If `colored2` gem has some support for "uncolorize", then we can get rid of `colorize` gem.

**Comment by mgrebenets** [comment]
I haven't tested it yet, still work in progress, but using `no_color` from `colored2` should do the same as `uncolorize` from `colorize`.

https://github.com/garriguv/danger-ruby-swiftformat/pull/11

**Comment by garriguv** [comment]
I have released `0.3.6` with these changes.
